### ISSUE TITLE
Invalid credentials but they're valid

### ISSUE THREAD

**Issue by CyanBook** [An0nimia/DeezloaderRMX_bot#3]
Titile explin this, this is the error:

```
Traceback (most recent call last):
  File "./dwsongs.py", line 767, in <module>
    downloa = deezloader.Login(setting.username, setting.password)
  File "/usr/local/lib/python3.5/dist-packages/deezloader/__init__.py", line 62, in __init__
    raise BadCredentials("Invalid password or username")
deezloader.BadCredentials: Invalid password or username
```

what can i do?

**Comment by An0nimia** [comment]
@CyanBook The password and the username are invalid

**Comment by CyanBook** [comment]
But they're valid. I just tested it! Should i change ip, implement tor on python or someting?

**Comment by An0nimia** [comment]
@CyanBook It's strange, no you don't need tor or change ip, maybe you have created a new account and you haven't checked confirm email
If this still doesn't work I suggest you to create a new account or say your credentials on Telegram to @An0nimia and try it by myself

**Comment by An0nimia** [comment]
Use arl token.
