### ISSUE TITLE
"too big to be sent"

### ISSUE THREAD

**Issue by filikili** [An0nimia/DeezloaderRMX_bot#4]
Thx for the bot!
But,
the new limit on size/length is ruining all the fun.

Can we have it raised or removed completely?

<img width="441" alt="Screen Shot 2019-04-23 at 21 54 11" src="https://user-images.githubusercontent.com/49931060/56629272-74691900-6612-11e9-9cc6-25eb4f89746b.png">

**Comment by An0nimia** [comment]
@filikili That is a bot api limitation, bot api can't send file bigger than 50mb

**Comment by An0nimia** [comment]
Sending files

There are three ways to send files (photos, stickers, audio, media, etc.):

    If the file is already stored somewhere on the Telegram servers, you don't need to reupload it: each file object has a file_id field, simply pass this file_id as a parameter instead of uploading. There are no limits for files sent this way.
    Provide Telegram with an HTTP URL for the file to be sent. Telegram will download and send the file. 5 MB max size for photos and 20 MB max for other types of content.
    Post the file using multipart/form-data in the usual way that files are uploaded via the browser. 10 MB max size for photos, 50 MB for other files.
